# Site settings
title: FEMUG AM
description: "Front-end Meet Up Group of Amazonas"
url: "https://femugam.github.io"




# Secondary Parameters
# baseurl: "/"
header-img: img/membros/povo.jpg
headercolor: "#eee"
logo: /img/logos/femug-icon.png

# Tertiary Parameters
github_username:  femugam
project_repository: femugam
disqus_shortname: femugam 
g-analytics: UA-75881392-1
altmetric: true

# Build settings
gems: [jekyll-paginate]
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# Jekyll Settings

defaults:
  -
    scope:
      path: "projects"
      type: "pages"
    values:
      layout: "project"
      header-img: "img/femug-icon.png"
